<a href="https://colab.research.google.com/github/abidshafee/dataAnalysis/blob/master/NumPy_allInOneNotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### **Initializing Array**

In [3]:
# 1D array
list = [1, 2, 3, 5]
np_array = np.array(list)
print(np_array)

[1 2 3 5]


In [4]:
# 2D array
np_array2d = np.array([[1, 2, 3, 4], [3, 2, 7, 9]])
print(np_array2d)

[[1 2 3 4]
 [3 2 7 9]]
